# Generated by Django 3.2.8 on 2021-10-31 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0002_rename_posttempat_post'),
        ('forum', '0004_alter_forum_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lokasi.post'),
            preserve_default=False,
        ),
    ]
