# Generated by Django 3.2.8 on 2021-11-04 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20211029_1357'),
        ('forum', '0005_forum_post_id'),
    ]

    operations = [
    ]
