# Generated by Django 3.2.8 on 2021-11-04 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0006_merge_0002_auto_20211029_1357_0005_forum_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='writer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
