# Generated by Django 3.2.8 on 2021-11-05 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_komentar_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='komentar',
            old_name='user_id',
            new_name='writer',
        ),
    ]
