# Generated by Django 3.2.8 on 2021-11-05 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_rename_user_id_komentar_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='komentar',
            old_name='writer',
            new_name='user_id',
        ),
    ]
