# Generated by Django 3.2.8 on 2021-10-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isi',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='foto',
            field=models.TextField(),
        ),
    ]
