# Generated by Django 3.2.8 on 2021-10-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0003_auto_20211029_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='judul',
            field=models.CharField(max_length=500),
        ),
    ]
