# Generated by Django 3.2.8 on 2021-10-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0004_alter_post_judul'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='penulis',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
    ]
