# Generated by Django 3.2.8 on 2021-10-29 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0005_auto_20211029_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentar',
            name='post_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artikel.post'),
            preserve_default=False,
        ),
    ]
