# Generated by Django 3.2.8 on 2021-11-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0007_komentar_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='komen',
            field=models.TextField(),
        ),
    ]
