# Generated by Django 3.2.8 on 2021-11-05 16:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artikel', '0011_alter_komentar_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Komentar',
            new_name='Comment',
        ),
    ]
