# Generated by Django 3.2.8 on 2021-11-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesan',
            name='message',
            field=models.TextField(),
        ),
    ]
