# Generated by Django 3.2.8 on 2021-10-29 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swab_vaksin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informasi',
            name='pengalaman',
        ),
        migrations.AddField(
            model_name='informasi',
            name='akurasi',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='informasi',
            name='deskripsi',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='informasi',
            name='efikasi',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='informasi',
            name='frekuensi',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='informasi',
            name='hasilTes',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='informasi',
            name='kategori',
            field=models.CharField(choices=[('swab', 'SWAB'), ('vaksin', 'VAKSIN')], default='swab', max_length=6),
        ),
        migrations.AddField(
            model_name='informasi',
            name='nama',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='informasi',
            name='price',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='informasi',
            name='produsen',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.CreateModel(
            name='Pengalaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengalaman', models.TextField(max_length=300)),
                ('penulis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
