# Generated by Django 3.2.8 on 2021-10-29 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swab_vaksin', '0002_auto_20211029_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwabInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='-', max_length=30)),
                ('price', models.CharField(default='-', max_length=30)),
                ('akurasi', models.CharField(default='-', max_length=30)),
                ('hasilTes', models.CharField(default='-', max_length=30)),
                ('deskripsi', models.CharField(default='-', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VaksinInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='-', max_length=30)),
                ('produsen', models.CharField(default='-', max_length=30)),
                ('frekuensi', models.CharField(default='-', max_length=30)),
                ('efikasi', models.CharField(default='-', max_length=30)),
                ('deskripsi', models.CharField(default='-', max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Pengalaman',
            new_name='Experience',
        ),
        migrations.DeleteModel(
            name='Informasi',
        ),
    ]
