# Generated by Django 3.2.8 on 2021-10-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swab_vaksin', '0003_auto_20211029_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swabinformation',
            old_name='hasilTes',
            new_name='durasi_hasil_tes',
        ),
        migrations.AlterField(
            model_name='swabinformation',
            name='deskripsi',
            field=models.TextField(default='-', max_length=500),
        ),
        migrations.AlterField(
            model_name='swabinformation',
            name='nama',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='vaksininformation',
            name='deskripsi',
            field=models.TextField(default='-', max_length=500),
        ),
    ]
