# Generated by Django 3.2.8 on 2021-10-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swab_vaksin', '0004_auto_20211029_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swabinformation',
            name='durasi_hasil_tes',
        ),
        migrations.AddField(
            model_name='swabinformation',
            name='prosedur',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
