# Generated by Django 3.2.8 on 2021-10-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swab_vaksin', '0005_auto_20211029_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swabinformation',
            name='prosedur',
        ),
        migrations.AddField(
            model_name='swabinformation',
            name='prosedu',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
