# Generated by Django 3.2.8 on 2021-11-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0002_rename_posttempat_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lokasi_pic',
            field=models.TextField(default=''),
        ),
    ]
