# Generated by Django 3.2.8 on 2021-11-04 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0003_post_lokasi_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='detailLokasi',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='namaLokasi',
        ),
    ]
