# Generated by Django 3.2.8 on 2021-11-04 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0004_auto_20211104_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='detailLokasi',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='namaLokasi',
            new_name='lokasi',
        ),
    ]
