# Generated by Django 3.2.8 on 2021-11-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userpic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
