# Generated by Django 3.2.8 on 2021-11-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_userpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userpic',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
